language: php

php:
  - 5.6
  - 7.0

env:
  - DRUPAL=8.1.x-dev

git:
  depth: 1

sudo: false

install:
  - TESTDIR=$(pwd)
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - composer self-update
  - composer global require drush/drush:dev-master

  - cd ..
  - drush dl drupal-${DRUPAL}

before_script:
  # Deploy the Drupal module into the Drupal modules directory.
  - rsync -rtlDPvc --exclude .git/ "${TESTDIR}" drupal-${DRUPAL}/modules/
  - cd drupal-${DRUPAL}

script:
  - ./vendor/bin/phpunit -c modules/typed_widget/phpunit.xml.dist --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt

after_script:
  - cat $TRAVIS_BUILD_DIR/coverage.txt
