language: php

matrix:
  include:
    - php: 5.6
      env: DRUPAL=8.1.x-dev
    - php: 7.0
      env: DRUPAL=8.1.x-dev
    - php: 5.6
      env: DRUPAL=8.2.x-dev
    - php: 5.6
      env: DRUPAL=8.3.x-dev
  allow_failures:
    - php: 5.6
      env: DRUPAL=8.3.x-dev
  fast_finish: true

git:
  depth: 1

sudo: false

install:
  - TESTDIR=$(pwd)
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - composer self-update
  - composer global require drush/drush:~8.1

  - cd ..
  - drush dl drupal-${DRUPAL}

before_script:
  # Deploy the Drupal module into the Drupal modules directory.
  - rsync -rtlDPvc --exclude .git/ "${TESTDIR}" drupal-${DRUPAL}/modules/
  - cd drupal-${DRUPAL}

script:
  - ./vendor/bin/phpunit -c modules/typed_widget/phpunit.xml.dist --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt

after_script:
  - cat $TRAVIS_BUILD_DIR/coverage.txt
