language: php

php:
  - 5.6
  - 7.0

env:
  - DRUPAL=8.1.x-dev

git:
  depth: 1

sudo: false

install:
  - TESTDIR=$(pwd)
  - DRUPALDIR=${TESTDIR}/../drupal
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  - composer self-update
  - composer global require drush/drush:dev-master

  - drush dl drupal-${DRUPAL} "${DRUPALDIR}"

before_script:
  # Deploy the Drupal module into the Drupal modules directory.
  - rsync -rtlDPvc --exclude .git/ "${TESDIR}" "${DRUPALDIR}/modules/"
  - cd "${DRUPALDIR}"

script:
  - ./vendor/bin/phpunit --bootstrap core/tests/bootstrap.php --coverage-text=$TRAVIS_BUILD_DIR/coverage.txt modules/typed_widget

after_script:
  - cat $TRAVIS_BUILD_DIR/coverage.txt